#!/usr/bin/env python3
"""
build-map.py — single source of truth for a codemap fragment set (project-agnostic).

Reads `fragments.config` (next to this script's parent skill dir) and the YAML-ish frontmatter of
every fragment under <docs_dir>, then regenerates:
  1. <docs_dir>/README.md   — the human index, grouped by category
  2. <skill_dir>/MAP.md     — source file -> fragment(s) routing/drift map

Behavior is entirely config-driven, so this file is copied verbatim into every project. No third-party
deps (hand-rolled frontmatter parser over the small subset we author). Run after editing a fragment:

    python3 .claude/skills/<proj>-context/scripts/build-map.py

Idempotent. Prints a summary + any fragment missing frontmatter (exit 1 on missing).
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

SCRIPT = Path(__file__).resolve()
SKILL_DIR = SCRIPT.parents[1]            # <scope-root>/.claude/skills/<proj>-context
REPO = SCRIPT.parents[4]                 # scope root = the dir containing .claude/ (NOT necessarily git root)
CONFIG = SKILL_DIR / "fragments.config"

MARK = "<!-- GENERATED by scripts/build-map.py — do not edit by hand; edit fragment frontmatter instead -->"


def load_config() -> dict:
    cfg = json.loads(CONFIG.read_text(encoding="utf-8")) if CONFIG.exists() else {}
    cfg.setdefault("docs_dir", "docs/context")
    cfg.setdefault("categories", [])     # ordered [{"dir":..,"label":..}]
    return cfg


def parse_frontmatter(text: str) -> dict | None:
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    fm: dict = {}
    key = None
    for raw in text[3:end].strip("\n").splitlines():
        line = raw.rstrip()
        if not line.strip():
            continue
        if line.startswith("  - ") or line.startswith("- "):
            if key:
                fm.setdefault(key, [])
                if isinstance(fm[key], list):
                    fm[key].append(line.split("- ", 1)[1].strip())
            continue
        if ":" in line:
            k, _, v = line.partition(":")
            key = k.strip()
            v = v.strip()
            if v in ("", "[]"):
                fm[key] = []
            elif v.startswith("[") and v.endswith("]"):
                fm[key] = [x.strip() for x in v[1:-1].split(",") if x.strip()]
            else:
                fm[key] = v
    return fm


def collect(docs: Path) -> list[dict]:
    frags = []
    for md in sorted(docs.rglob("*.md")):
        rel = md.relative_to(docs)
        if rel.name == "README.md":
            continue
        fm = parse_frontmatter(md.read_text(encoding="utf-8"))
        frags.append({
            "path": str(rel),
            "category": rel.parts[0] if len(rel.parts) > 1 else "",
            "title": (fm or {}).get("title") or md.stem,
            "status": (fm or {}).get("status", "?"),
            "sources": (fm or {}).get("sources", []) or [],
            "related": (fm or {}).get("related", []) or [],
            "has_fm": fm is not None,
        })
    return frags


def category_order(cfg: dict, frags: list[dict]) -> list[tuple[str, str]]:
    """Configured categories first (in order), then any extra dirs found, then root-level ('')."""
    order = [(c["dir"], c.get("label", c["dir"])) for c in cfg["categories"]]
    known = {d for d, _ in order}
    extras = sorted({f["category"] for f in frags if f["category"] and f["category"] not in known})
    order += [(d, d) for d in extras]
    if any(f["category"] == "" for f in frags):
        order.append(("", "Other"))
    return order


def render_readme(cfg: dict, frags: list[dict]) -> str:
    proj = cfg.get("project", "this project")
    skill = SKILL_DIR.name                   # actual skill dir (e.g. arcterm-context) — not the display name
    out = [f"# {proj} — design fragments", "", MARK, "",
           "Small, focused fragments that mirror the codebase. Each declares the source files it",
           "covers (frontmatter `sources:`). Regenerate this index with",
           f"`python3 .claude/skills/{skill}/scripts/build-map.py`.", ""]
    by_cat: dict[str, list[dict]] = {}
    for f in frags:
        by_cat.setdefault(f["category"], []).append(f)
    for cat, label in category_order(cfg, frags):
        items = by_cat.get(cat, [])
        if not items:
            continue
        out += [f"## {label}", "", "| Fragment | Status | Covers |", "|---|---|---|"]
        for f in sorted(items, key=lambda x: x["path"]):
            covers = ", ".join(Path(s).name for s in f["sources"][:4]) or "—"
            if len(f["sources"]) > 4:
                covers += ", …"
            out.append(f"| [{f['title']}]({f['path']}) | {f['status']} | {covers} |")
        out.append("")
    return "\n".join(out) + "\n"


def render_map(cfg: dict, frags: list[dict]) -> str:
    proj = cfg.get("project", "project")
    skill = SKILL_DIR.name
    rev: dict[str, list[str]] = {}
    for f in frags:
        for s in f["sources"]:
            rev.setdefault(s, []).append(f["path"])
    out = [f"# {proj} context MAP", "", MARK, "",
           "Reverse index: **source file → the fragment(s) that document it.** Used by the",
           f"`{skill}` skill to load the right fragment when you touch a file and to detect drift.",
           "Regenerate via `scripts/build-map.py`.", "",
           "## Source file → fragment(s)", "", "| Source file | Documented in |", "|---|---|"]
    for src in sorted(rev):
        out.append(f"| `{src}` | {', '.join(sorted(set(rev[src])))} |")
    out += ["", "## Fragment → sources", "", "| Fragment | Sources |", "|---|---|"]
    for f in sorted(frags, key=lambda x: x["path"]):
        srcs = ", ".join(f"`{Path(s).name}`" for s in f["sources"]) or "_(no source files — narrative/reference)_"
        out.append(f"| `{f['path']}` | {srcs} |")
    return "\n".join(out) + "\n"


def main() -> int:
    cfg = load_config()
    docs = REPO / cfg["docs_dir"]
    if not docs.exists():
        print(f"docs dir not found: {docs}", file=sys.stderr)
        return 2
    frags = collect(docs)
    (docs / "README.md").write_text(render_readme(cfg, frags), encoding="utf-8")
    (SKILL_DIR / "MAP.md").write_text(render_map(cfg, frags), encoding="utf-8")
    missing = [f["path"] for f in frags if not f["has_fm"]]
    n_src = len({s for f in frags for s in f["sources"]})
    print(f"✓ {len(frags)} fragments · {n_src} mapped source files")
    print(f"  wrote {(docs / 'README.md').relative_to(REPO)}")
    print(f"  wrote {(SKILL_DIR / 'MAP.md').relative_to(REPO)}")
    if missing:
        print("⚠ fragments missing frontmatter:", ", ".join(missing))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
