// Codable mirrors of the puzzle contract (schemas/*.schema.json).
// Display-side only: reconstruction and scoring stay in the Rust engine;
// the app renders puzzles and looks up precomputed outcomes.

import Foundation

struct Pack: Decodable, Hashable {
    let id: String
    let title: String
    let description: String?
    let toolchain: String
    let order: [String]
    /// Display-only deck identity (SF Symbol name + named accent color).
    let icon: String?
    let accent: String?
}

struct Puzzle: Decodable, Identifiable, Hashable {
    let id: String
    let version: Int
    let title: String
    let track: String
    let concepts: [String]
    let difficulty: Int
    let goal: String
    let template: String?
    let interaction: Interaction
    /// Absent on lesson puzzles (reading nodes are never scored).
    let scoring: Scoring?
    let hints: [String]
    let explanation: String
}

struct Scoring: Decodable, Hashable {
    let primary: String
    let secondary: [String]?
    let fluent: [String: Int]
    let optimal: [String: Int]

    /// Metrics in display order: primary first, then declared secondaries.
    var displayOrder: [String] {
        [primary] + (secondary ?? []).filter { $0 != primary }
    }
}

struct Slot: Decodable, Identifiable, Hashable {
    let id: String
    let original: String?
    let label: String?
    let choices: [Choice]
}

struct Choice: Decodable, Identifiable, Hashable {
    let id: String
    let text: String
}

struct Block: Decodable, Identifiable, Hashable {
    let id: String
    let text: String
}

struct Candidate: Decodable, Identifiable, Hashable {
    let id: String
    let code: String
}

/// One block of a lesson: flowing prose or a highlighted code snippet.
enum LessonSection: Decodable, Hashable {
    case prose(text: String)
    case code(code: String, caption: String?)

    private enum CodingKeys: String, CodingKey {
        case kind, text, code, caption
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        switch try c.decode(String.self, forKey: .kind) {
        case "prose":
            self = .prose(text: try c.decode(String.self, forKey: .text))
        case "code":
            self = .code(
                code: try c.decode(String.self, forKey: .code),
                caption: try c.decodeIfPresent(String.self, forKey: .caption)
            )
        case let other:
            throw DecodingError.dataCorruptedError(
                forKey: .kind, in: c,
                debugDescription: "unknown lesson section kind \(other)"
            )
        }
    }
}

enum Interaction: Decodable, Hashable {
    case slotSelection(slots: [Slot])
    case minimalEdit(slots: [Slot])
    case blockArrangement(fixedPrefix: String, blocks: [Block], fixedSuffix: String)
    case bestSolution(candidates: [Candidate])
    case lesson(sections: [LessonSection])

    var slots: [Slot]? {
        switch self {
        case .slotSelection(let slots), .minimalEdit(let slots): slots
        default: nil
        }
    }

    var isLesson: Bool {
        if case .lesson = self { true } else { false }
    }

    private enum CodingKeys: String, CodingKey {
        case type, slots, blocks, candidates, sections
        case fixedPrefix = "fixed_prefix"
        case fixedSuffix = "fixed_suffix"
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        switch try c.decode(String.self, forKey: .type) {
        case "slot-selection":
            self = .slotSelection(slots: try c.decode([Slot].self, forKey: .slots))
        case "minimal-edit":
            self = .minimalEdit(slots: try c.decode([Slot].self, forKey: .slots))
        case "block-arrangement":
            self = .blockArrangement(
                fixedPrefix: try c.decode(String.self, forKey: .fixedPrefix),
                blocks: try c.decode([Block].self, forKey: .blocks),
                fixedSuffix: try c.decode(String.self, forKey: .fixedSuffix)
            )
        case "best-solution":
            self = .bestSolution(candidates: try c.decode([Candidate].self, forKey: .candidates))
        case "lesson":
            self = .lesson(sections: try c.decode([LessonSection].self, forKey: .sections))
        case let other:
            throw DecodingError.dataCorruptedError(
                forKey: .type, in: c,
                debugDescription: "unknown interaction type \(other)"
            )
        }
    }
}

// MARK: - Concepts (content/concepts — the tap-to-learn skill library)

struct Concept: Decodable, Identifiable, Hashable {
    let id: String
    let title: String
    let summary: String
    let lecture: [String]
    let example: ConceptExample?
}

struct ConceptExample: Decodable, Hashable {
    let code: String
    let caption: String?
}

// MARK: - Outcomes sidecar (generated by the puzzle linter)

struct Outcomes: Decodable {
    let puzzleId: String
    let puzzleVersion: Int
    let toolchain: String
    let outcomes: [String: EvalResult]

    private enum CodingKeys: String, CodingKey {
        case outcomes, toolchain
        case puzzleId = "puzzle_id"
        case puzzleVersion = "puzzle_version"
    }
}

struct EvalResult: Decodable, Hashable {
    let status: Status
    let rank: Rank?
    let metrics: [String: Int]
    let diagnostics: [Diagnostic]

    enum Status: String, Decodable {
        case solved
        case compileError = "compile_error"
        case testFailure = "test_failure"
        case invalid
    }

    enum Rank: String, Decodable, Comparable {
        case solved, fluent, optimal

        private var order: Int {
            switch self { case .solved: 0; case .fluent: 1; case .optimal: 2 }
        }

        static func < (lhs: Rank, rhs: Rank) -> Bool { lhs.order < rhs.order }
    }
}

struct Diagnostic: Hashable {
    let category: String
    let message: String
    let slotIds: [String]
    let rustCode: String?
}

extension Diagnostic: Decodable {
    private enum CodingKeys: String, CodingKey {
        case category, message
        case slotIds = "slot_ids"
        case rustCode = "rust_code"
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.init(
            category: try c.decode(String.self, forKey: .category),
            message: try c.decode(String.self, forKey: .message),
            slotIds: try c.decodeIfPresent([String].self, forKey: .slotIds) ?? [],
            rustCode: try c.decodeIfPresent(String.self, forKey: .rustCode)
        )
    }
}
